# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0f391ce424825e9a307a1b5b128126bef7ae0c5802f4791673036ceca487e1f51d87031cff07f3ad7997afe76c7ef7512915956c1a1e730d37d4f15a662ae7

test:
  secret_key_base: b2401824bdaee7fa2f3a535e5c2ba446c37f41ebcbfb502d86294c4a9f0858b454248d7fcbb933f146d27f3a4b3c6e79224eb87d79b683ec08b061156ae6e45b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
